version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/health_tech
      - ./env:/app/health_tech/env
    environment:
      UVICORN_WORKERS: 4
      DB_URL: postgresql://health_tech_user_dev:Password!@postgres:5432/health_tech_db_dev
    depends_on:
      - postgres
  postgres:
    container_name: postgres_db
    image: postgres
    hostname: postgres
    volumes:
      - "/postgres-data/:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      POSTGRES_USER: health_tech_user_dev
      POSTGRES_PASSWORD: Password!
      POSTGRES_DB: health_tech_db_dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U health_tech_user_dev -d health_tech_db_dev -h localhost -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
